# Site settings
email: max@maxwellwenger.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-93216105-2

# SEO settings
title: Maxwell Wenger
description: Max Wenger's thoughts on programming and networking.
url: "http://blog.maxwellwenger.com"
twitter_username: maxwenger
default_img: 

# Profile settings
name: Maxwell Wenger
profile_img: profile.png
profile: 
social:
  github: http://github.com/maxwenger/
  linkedin: https://www.linkedin.com/in/maxwell-wenger/
  twitter: https://twitter.com/maxwellwenger/
  address-card: http://www.maxwellwenger.com/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
